version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al 8000 de tu máquina
    volumes:
      - .:/app  # Sincroniza el directorio local con el contenedor
    environment:
      - MONGO_URI=mongodb://mongo:27017/trafico_caba
    depends_on:
      - mongo  # Asegura que el servicio de MongoDB se levante antes

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"  # Mapea el puerto de MongoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: